DROP TABLE IF EXISTS comment_likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS stalls;
DROP TABLE IF EXISTS food_types;
DROP TABLE IF EXISTS canteens;
DROP TABLE IF EXISTS users;
